

def hex_to_ass(hex_color: str, alpha: int = 0) -> str:
    h = hex_color.strip().lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        raise ValueError(f"bad colour '{hex_color}', expected #RRGGBB")
    int(h, 16)
    r, g, b = h[0:2], h[2:4], h[4:6]
    return f"&H{alpha:02X}{b}{g}{r}".upper()


def to_timestamp(seconds: float) -> str:
    if seconds < 0:
        seconds = 0.0
    total_cs = int(round(seconds * 100))
    cs = total_cs % 100
    total_s = total_cs // 100
    s = total_s % 60
    m = (total_s // 60) % 60
    h = total_s // 3600
    return f"{h}:{m:02d}:{s:02d}.{cs:02d}"


def escape(text: str) -> str:
    return (
        text.replace("\\", "")
        .replace("{", "(")
        .replace("}", ")")
        .replace("\n", " ")
        .replace("\r", " ")
    )


def build_header(style: dict, width: int, height: int) -> str:
    fields = [
        "Default",
        style["font"],
        str(style["size"]),
        hex_to_ass(style["base_color"]),
        hex_to_ass(style["active_color"]),
        hex_to_ass(style["outline_color"]),
        hex_to_ass(style["shadow_color"]),
        "-1", "0", "0", "0", "100", "100", "0", "0",
        "1",
        f"{style['outline']:g}",
        f"{style['shadow']:g}",
        "5",
        str(style["margin_h"]), str(style["margin_h"]), "0",
        "1",
    ]
    return (
        "[Script Info]\n"
        "; Generated by capkit_lite\n"
        "ScriptType: v4.00+\n"
        f"PlayResX: {width}\n"
        f"PlayResY: {height}\n"
        "WrapStyle: 2\n"
        "ScaledBorderAndShadow: yes\n"
        "YCbCr Matrix: None\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: {','.join(fields)}\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, "
        "MarginV, Effect, Text\n"
    )


def _render_text(cue: Cue, active: int, style: dict) -> str:
    base_tag = f"{{\\c{hex_to_ass(style['base_color'])}\\fscx100\\fscy100}}"
    scale = int(round(style["pop"] * 100))
    active_tag = f"{{\\c{hex_to_ass(style['active_color'])}\\fscx{scale}\\fscy{scale}}}"
    parts = []
    for idx, w in enumerate(cue.words):
        token = w.text.upper() if style["uppercase"] else w.text
        token = escape(token)
        parts.append(f"{active_tag}{token}" if idx == active else f"{base_tag}{token}")
    return " ".join(parts)


def build_events(cues, style: dict) -> List[str]:
    events: List[str] = []
    for cue in cues:
        if not cue.words:
            continue
        last = len(cue.words) - 1
        for i, word in enumerate(cue.words):
            start = word.start
            end = cue.words[i + 1].start if i < last else cue.end
            if end <= start:
                end = start + 0.04
            text = _render_text(cue, active=i, style=style)
            events.append(
                f"Dialogue: 0,{to_timestamp(start)},{to_timestamp(end)},"
                f"Default,,0,0,0,,{text}"
            )
    return events


def write_ass(path: str, cues, style: dict, width: int, height: int) -> None:
    content = build_header(style, width, height) + "\n".join(build_events(cues, style)) + "\n"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
